# Generated by Django 5.0.6 on 2024-06-02 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_courseregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(1, 'COMING-SOON'), (1, 'IN-STOCK'), (3, 'OUT-OF-STOCK')], default=2)),
                ('expired_at', models.DateTimeField(null=True)),
                ('seo_title', models.CharField(max_length=500, null=True)),
                ('seo_description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_course', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_course_creator', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_product', to='store.product')),
            ],
        ),
    ]
