# Generated by Django 5.0.6 on 2024-05-30 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'text'), (2, 'pdf'), (3, 'video'), (4, 'webinar'), (5, 'scorm'), (6, 'quiz'), (7, 'assignment'), (8, 'survey')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='m_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(db_column='deleted_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
