# Generated by Django 5.0.6 on 2024-05-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_textmodule'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE text_modules MODIFY column track_completion tinyint(1) NOT NULL DEFAULT 0'),
    ]
