# Generated by Django 5.0.6 on 2024-05-31 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_track_completion_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.SmallIntegerField(choices=[(1, 'youtube'), (2, 'in-house')])),
                ('url', models.CharField(max_length=512)),
                ('cover_url', models.CharField(max_length=512)),
                ('disable_skip', models.BooleanField(default=True)),
                ('track_completion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='video_created', to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.PROTECT, related_name='video_module', to='modules.module')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_modules',
            },
        ),
        migrations.RunSQL('ALTER TABLE video_modules MODIFY COLUMN track_completion tinyint(1) NOT NULL DEFAULT 0')
    ]
