# Generated by Django 5.0.6 on 2024-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_videomodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodule',
            name='cover_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
