# Generated by Django 5.0.6 on 2024-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_updated_at_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_disabled',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0),
        ),
    ]
