# Generated by Django 5.0.6 on 2024-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_storeaddress_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
