# Generated by Django 5.0.6 on 2024-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_storeaddress_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
